// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-z3DvyoG9uotM_E261WmQbpUl3RQEPyY',
    appId: '1:467520563806:web:3fe4eec3c7ef64f947a2cf',
    messagingSenderId: '467520563806',
    projectId: 'appli-10',
    authDomain: 'appli-10.firebaseapp.com',
    storageBucket: 'appli-10.appspot.com',
    measurementId: 'G-BZ7T98R3VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPsN4zThgwg5d4w5jETOHxAIuU-sdOkoI',
    appId: '1:467520563806:android:2bb97f3c259cbdf047a2cf',
    messagingSenderId: '467520563806',
    projectId: 'appli-10',
    storageBucket: 'appli-10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPoPfUFcFPYX2Y_s9Kg0O1aZWTWyckzO0',
    appId: '1:467520563806:ios:42379e2eb91b7ce847a2cf',
    messagingSenderId: '467520563806',
    projectId: 'appli-10',
    storageBucket: 'appli-10.appspot.com',
    iosClientId:
        '467520563806-5kkjuoqdp55eo266c6ls0aeennpcnf4f.apps.googleusercontent.com',
    iosBundleId: 'sn.alim.appli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPoPfUFcFPYX2Y_s9Kg0O1aZWTWyckzO0',
    appId: '1:467520563806:ios:42379e2eb91b7ce847a2cf',
    messagingSenderId: '467520563806',
    projectId: 'appli-10',
    storageBucket: 'appli-10.appspot.com',
    iosClientId:
        '467520563806-5kkjuoqdp55eo266c6ls0aeennpcnf4f.apps.googleusercontent.com',
    iosBundleId: 'sn.alim.appli',
  );
}
